/*
 * DMA_Cfg.c
 *
 *  Created on: Apr 15, 2020
 *      Author: MOSTAFA
 */


#include "DMA.h"
#include "DMA_Cfg.h"



const DMA_Config DMA_Configure[MAX_NUMBER_OF_CHANNELS]={

		{
				.Mem2Mem= MEMORY2PERIPHERAL,
				.PL     = PRIORITY_LOW,
				.MSIZE  = MEMORY_SIZE_1_BYTE,
				.PSIZE  = PERIPHERAL_SIZE_1_BYTE,
				.MINC   = MEMORY_INCREMENT_ON,
				.PINC   = PERIPHERAL_INCREMENT_OFF,
				.CIRC   = CIRCULER_INT_OFF,
				.DIR    = DIR_MEMORY_TO_PERI,
				.TEIE   = TRANSFER_ERROR_INT_OFF,
				.HTIE   = HALF_TRANSFER_INT_OFF,
				.TCIE   = TRANSFER_COMP_INT_ON,
				.ChannelNumber = CHANNEL_FOUR
		},
		{
				.Mem2Mem= MEMORY2PERIPHERAL,
				.PL     = PRIORITY_MEDIUM,
				.MSIZE  = MEMORY_SIZE_1_BYTE,
				.PSIZE  = PERIPHERAL_SIZE_1_BYTE,
				.MINC   = MEMORY_INCREMENT_ON,
				.PINC   = PERIPHERAL_INCREMENT_OFF,
				.CIRC   = CIRCULER_INT_OFF,
				.DIR    = DIR_PERI_TO_MEMORY,
				.TEIE   = TRANSFER_ERROR_INT_OFF,
				.HTIE   = HALF_TRANSFER_INT_OFF,
				.TCIE   = TRANSFER_COMP_INT_ON,
				.ChannelNumber = CHANNEL_FIVE
		},
		{
				.Mem2Mem= MEMORY2MEMORY,
				.PL     = PRIORITY_LOW,
				.MSIZE  = MEMORY_SIZE_1_BYTE,
				.PSIZE  = PERIPHERAL_SIZE_1_BYTE,
				.MINC   = MEMORY_INCREMENT_ON,
				.PINC   = PERIPHERAL_INCREMENT_ON,
				.CIRC   = CIRCULER_INT_OFF,
				.DIR    = DIR_PERI_TO_MEMORY,
				.TEIE   = TRANSFER_ERROR_INT_OFF,
				.HTIE   = HALF_TRANSFER_INT_OFF,
				.TCIE   = TRANSFER_COMP_INT_ON,
				.ChannelNumber = CHANNEL_ONE
		}

};
